import Navigation from '@/components/navigation'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='p-5'>
        <div className="relative">
          <Navigation />
          <div className="py-10">
            <div className="block max-w-[38rem] mx-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
